pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - master
    - feature/*
    - bug/*

pr:
  branches:
    include:
    - master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    architecture: 'x64'

- script: |
    pip install setuptools
    pip install awscli
  displayName: 'Installing AWS CLI'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- script: |
    docker run --rm -d --name rapido-pg \
     -e POSTGRES_PASSWORD=admin \
     -p 5432:5432 \
     postgres:10.7
  displayName: 'Starting local PG'

- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: custom
    customCommand: 'run test'
  env:
    DB_USER: $(LOCAL_DB_USER)
    DB_PASSWORD: $(LOCAL_DB_PASSWORD)
    HOST: $(LOCAL_HOST)
    PORT: $(LOCAL_PORT)

- task: Npm@1
  displayName: 'Deploying functions to DEV'
  inputs:
    command: custom
    customCommand: 'run dev-deploy'
  env:
    AWS_ACCESS_KEY_ID: $(DEV_AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(DEV_AWS_SECRET_ACCESS_KEY)
    DB_USER: $(DEV_DB_USER)
    DB_PASSWORD: $(DEV_DB_PASSWORD)
    HOST: $(DEV_HOST)
    PORT: $(DEV_PORT)
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

- task: Npm@1
  displayName: 'Deploying functions to PROD'
  inputs:
    command: custom
    customCommand: 'run dev-deploy'
  env:
    AWS_ACCESS_KEY_ID: $(PROD_AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(PROD_AWS_SECRET_ACCESS_KEY)
    DB_USER: $(PROD_DB_USER)
    DB_PASSWORD: $(PROD_DB_PASSWORD)
    HOST: $(PROD_HOST)
    PORT: $(PROD_PORT)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
