-- Order status types
INSERT INTO orders.order_status VALUES (1, 'Incomplete');
INSERT INTO orders.order_status VALUES (2, 'Payed');
INSERT INTO orders.order_status VALUES (3, 'Delivered');
INSERT INTO orders.order_status VALUES (4, 'Cancelled');
INSERT INTO orders.order_status VALUES (5, 'Returned');
-- Countries
INSERT INTO orders.country VALUES (1, 'United Kingdom');
-- Vat
INSERT INTO orders.vat VALUES (1, 0.20);
-- Delivery Cost
INSERT INTO orders.delivery_cost VALUES (1, 0, "Standard delivery");
INSERT INTO orders.delivery_cost VALUES (2, 50, "Next day delivery");
-- Products
INSERT INTO orders.products (id, unit_price, item_name) VALUES (1, 222.99, 'Item Description 1 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (2, 219.00, 'Item Description 2 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (3, 229.17, 'Item Description 3 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (4, 79.00, 'Item Description 4 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (5, 49.00, 'Item Description 5 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (6, 253.00, 'Item Description 6 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (7, 49.00, 'Item Description 7 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (8, 269.41, 'Item Description 8 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (9, 49.99, 'Item Description 9 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (10, 14.00, 'Item Description 10 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (11, 41990.00, 'Item Description 11 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (12, 41990.00, 'Item Description 12 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (13, 41990.00, 'Item Description 13is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (14, 41990.00, 'Item Description 14 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (15, 41990.00, 'Item Description 15 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (16, 10990.00, 'Item Description 16 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (17, 39990.00, 'Item Description 17 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (18, 39990.00, 'Item Description 18 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (19, 214990.00, 'Item Description 19 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (20, 104990.00, 'Item Description 20 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (21, 990.00, 'Item Description 21 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (22, 790.00, 'Item Description 22 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (23, 890.00, 'Item Description 23 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (24, 890.00, 'Item Description 24 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (25, 890.00, 'Item Description 25 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (26, 999.00, 'Item Description 26 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (27, 1999.00, 'Item Description 27 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (28, 269.41, 'Item Description 28 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (29, 269.41, 'Item Description 29 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (30, 269.41, 'Item Description 30 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (31, 16499.00, 'Item Description 31 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (32, 6499.00, 'Item Description 32 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (33, 1649.00, 'Item Description 33 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (34, 1499.00, 'Item Description 34 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (35, 1499.00, 'Item Description 35 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (36, 5.99, 'Item Description 36 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (37, 9.99, 'Item Description 37 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (38, 2.99, 'Item Description 38 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (39, 1.99, 'Item Description 39 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (40, 14.82, 'Item Description 40 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (41, 19.99, 'Item Description 41 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (42, 19.99, 'Item Description 42 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (43, 31.67, 'Item Description 43 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (44, 25.60, 'Item Description 44 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (45, 32.39, 'Item Description 45 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (46, 32.39, 'Item Description 46 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (47, 21.71, 'Item Description 47 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (48, 17.71, 'Item Description 48 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (49, 25.71, 'Item Description 49 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (50, 25.71, 'Item Description 50 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (51, 16499.00, 'Item Description 51 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (52, 11999.00, 'Item Description 52 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (53, 17900.00, 'Item Description 53 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (54, 13290.00, 'Item Description 54 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (55, 11999.00, 'Item Description 55 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (56, 20000.00, 'Item Description 56 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (57, 20000.00, 'Item Description 57 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (58, 25000.00, 'Item Description 58 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (59, 35000.00, 'Item Description 59 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (60, 10000.00, 'Item Description 60 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (61, 11000.00, 'Item Description 61 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (62, 12000.00, 'Item Description 62 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (63, 16300.00, 'Item Description 63 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (64, 10300.00, 'Item Description 64 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (65, 6300.00, 'Item Description 65 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (66, 2000.00, 'Item Description 66 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (67, 3000.00, 'Item Description 67 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (68, 3000.00, 'Item Description 68 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (69, 3900.00, 'Item Description 69 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (70, 6600.00, 'Item Description 70 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (71, 1000.00, 'Item Description 71 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (72, 2000.00, 'Item Description 72 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (73, 2000.00, 'Item Description 73 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (74, 2670.00, 'Item Description 74 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (75, 970.00, 'Item Description 75 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (76, 870.00, 'Item Description 76 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (77, 870.00, 'Item Description 77 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (78, 570.00, 'Item Description 78 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (79, 2570.00, 'Item Description 79 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (80, 1370.00, 'Item Description 80 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (81, 1370.00, 'Item Description 81 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (82, 500.00, 'Item Description 82 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (83, 999.00, 'Item Description 83 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (84, 2199.00, 'Item Description 84 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (85, 3000.00, 'Item Description 85 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (86, 30.00, 'Item Description 86 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (87, 35.00, 'Item Description 87 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (88, 38.00, 'Item Description 88 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (89, 28.00, 'Item Description 89 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (90, 29.00, 'Item Description 90 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (91, 29.00, 'Item Description 91 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (92, 32.00, 'Item Description 92 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (93, 32.00, 'Item Description 93 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (94, 28.00, 'Item Description 94 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (95, 29.00, 'Item Description 95 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (96, 30.00, 'Item Description 96 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (97, 31.00, 'Item Description 97 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (98, 32.00, 'Item Description 98 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (99, 33.00, 'Item Description 99 is going to come in here once added');
INSERT INTO orders.products (id, unit_price, item_name) VALUES (100, 34.00, 'Item Description 100 is going to come in here once added');
